trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    # Navigate to the 'front' directory
    cd front

    # Install dependencies (assuming npm is used)
    npm install

    # Build the frontend application
    npm run build
  displayName: 'Install and Build Frontend'
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: 'front/dist'
    artifactName: 'frontend-artifact'
    
  displayName: 'Publish Frontend Build Artifact'

- script: |
    # Navigate to the 'back' directory
    cd back

    # Install dependencies (assuming npm is used)
    npm install

    # Build the backend application (replace this with your build command)
    npm run build
  displayName: 'Install and Build Backend'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: 'back/dist'  # Update this path according to your backend build output directory
    artifactName: 'backend-artifact'
  displayName: 'Publish Backend Build Artifact' 
- task: CopyFiles@2
  inputs:
    SourceFolder: 'terraform'
    Contents: '**'  # Include all files in the 'terraform' directory
    TargetFolder: '$(Build.ArtifactStagingDirectory)/terraform'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/terraform'
    ArtifactName: 'terraform-files'
    publishLocation: 'Container' 
